config/routes.rb
Rails.application.routes.draw do

  root :to => 'welcome#home'

  namespace :dashboard do
    root :to => 'base#index'
    get 'base/index'
    post "/search", to: "base#search"
    get "/search", to: "base#search"
    resource :user, only: [:edit, :update]
    resources :skills, only: [:index, :show]
    resources :projects do
      get 'all', :on => :collection
    end
    resources :volunteerings, only: [:index, :create, :update, :edit]
  end

  # scope :existing do
  #   resources :users, only: [:show]
  # end

  get 'dashboard/volunteerings/new_signup' => 'dashboard/volunteerings#new_signup'

  get 'dashboard/volunteerings/new_recruit' => 'dashboard/volunteerings#new_recruit'

  # get '/welcome/dashboard' => 'welcome#dashboard'
  get '/users/registration' => 'users#registration'
  get 'users/new/confirmation' => 'users#confirmation'
  put 'users/update' => 'users#update'
  get '/welcome/home' => 'welcome#home'


  devise_for :users, except: [:index], controllers: {
    sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks', users: 'users'
  }, :path => 'devise'

  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :users, except: [:index, :destroy, :show]


  post 'slack/search'

  post 'slack/project_search'

  post 'slack/project_skills_search'

  post 'slack/project_list'

  get '/admin/projects/upload_csv', to: 'admin/projects#upload_csv', as: :admin_projects_upload_csv

  get '/admin/users/upload_csv', to: 'admin/users#upload_csv', as: :admin_users_upload_csv

  post 'admin/projects/import_data', to: 'admin/projects#import_data', as: :admin_projects_import_data
        
  post 'admin/users/import_data', to: 'admin/users#import_data', as: :admin_users_import_data

  post 'admin/projects/bulk_post', to: 'admin/projects#bulk_post', as: :admin_projects_bulk_post

  post 'admin/users/bulk_post', to: 'admin/users#bulk_post', as: :admin_users_bulk_post

  # uncomment these lines after rake db:create is finished
  #devise_for :admin_users, ActiveAdmin::Devise.config

  #ActiveAdmin.routes(self)



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/skill.rb
class Skill < ApplicationRecord

  has_and_belongs_to_many :project_needs, class_name: "Project", join_table: "needs_categories"

  has_and_belongs_to_many :users

  has_and_belongs_to_many :projects, join_table: "projects_skills"

  scope :tech_skills, -> () { where(tech: true).order("name ASC") }
  scope :non_tech_skills, -> () { where("tech = false OR tech IS NULL").order("name ASC") }
  scope :match_skill, -> (str) { where("lower(name) = lower(?)", str_or_arr) }
  scope :match_skills, -> (arr) { where("lower(name) IN (?)", arr.map(&:downcase)) }

  scope :simple_search,   -> (q) do
    q = "%#{q}%"
    where("name ILIKE ?", q).order("created_at ASC")
  end

  audited

    def self.match_with_airtable(airtable_skills: , tech:)
      airtable_skills.map do |skill|
        Skill.where('lower(name) = ?', skill.downcase).first_or_create(:name=>skill, :tech=>tech).id
      end
    end

    def designate
      case self.tech
      when true
        "Yes"
      when false
        "No"
      when nil
        "Unassigned"
      end
    end

    def self.tech_designated(designation =      'Unassigned')
      self.all.select{|skill| skill.designate == designation }
    end

    ransacker :by_tech_designation, { formatter: proc { |string|
      data = self.tech_designated(string).map(&:id)
      data = data.present? ? data : nil
    }, callable: proc { |parent|
      parent.table[:id]}}

end

app/controllers/dashboard/base_controller.rb
class Dashboard::BaseController < ApplicationController
  before_action :authenticate_user!
  layout "dashboard"

  def index

  end

  def search
    @results = {skills: Skill.simple_search(params[:q]), projects: Project.simple_search(params[:q]), users: UserSearch.new({text: params[:q]}).call}
  end
end

app/controllers/dashboard/projects_controller.rb
class Dashboard::ProjectsController < Dashboard::BaseController
  inherit_resources
  include SlackHelpers
  
  def all
    @projects = Project.order("name ASC").includes(:stacks).where(:mission_aligned => true)
  end

  def create
    @project = Project.new(project_params)

    @project.get_ids_from_names(project_params[:tech_stack_names].split(", "), project_params[:non_tech_stack_names].split(", "), project_params[:needs_category_names].split(", "))

    if @project.valid?
      @project.project_created = Time.current
      @project.save
      redirect_to dashboard_projects_path
    else
      render :edit
    end
  end
  
  def show
    @project = Project.find(params[:id])
    @channel = @project.slack_channel_for_url
  end

  def edit
    @channels = SlackHelpers.get_slack_channels
    skills = resource.tech_stack.map{|s| s.name}.join(",")
    print skills
    
  end

  def update

    resource.assign_attributes(project_params)
    
    if params[:slack_channel]
      
      resource.get_slack_channel_id(params[:slack_channel])
    end

    resource.get_ids_from_names(project_params[:tech_stack_names].split(", "), project_params[:non_tech_stack_names].split(", "), project_params[:needs_category_names].split(", "))

    if resource.save
      redirect_to dashboard_projects_path
    else
      render :edit
    end

  end

  private

  
  def begin_of_association_chain
    current_user
  end

  def project_params
    params.require(:project).permit(:name, :description, :website, :slack_channel, :active_contributors, :project_created, :mission_accomplished, :needs_pain_points_narrative, :org_structure, :project_mgmt_url, :summary_test, :repository, :software_license_url, :values_screening, :working_doc, :full_release_features, :attachments, :tech_stack_names, :needs_category_names, :non_tech_stack_names, business_models: [],  legal_structures: [], oss_license_types: [], project_applications: [],  lead_ids: [], status: [], master_channel_list: [])
  end
end

app/controllers/dashboard/skills_controller.rb
class Dashboard::SkillsController < Dashboard::BaseController
  inherit_resources
  before_action :authenticate_user!

  def show
    @projects_having = resource.projects.where(:mission_aligned => true)
    @projects_needing = resource.project_needs.where(:mission_aligned => true)
    @users_having = resource.users.where(:optin => true)
  end

  
end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < Dashboard::BaseController
  inherit_resources
  defaults :singleton => true
  
  def edit
    current_user.valid?
  end

  def update
    if current_user.update(user_params)
      redirect_to dashboard_root_path
    else
      render :edit
    end
  end

  protected
    def resource
      current_user
    end

  private

    def user_params
      params.require(:user).permit(
        :edit, :anonymous, :join_reason,
        :overview, :location, :tech_skill_names, :non_tech_skill_names,
        :optin, :phone, :read_code_of_conduct,
        :verification_urls, :hear_about_us, :is_approved, :gender_pronouns, :additional_info
      )
    end
end

app/controllers/dashboard/volunteerings_controller.rb
class Dashboard::VolunteeringsController < Dashboard::BaseController
    inherit_resources
    include ProjectsHelper

    before_action :get_contributor_slack_information, only: :edit

    def index
      @volunteerings = current_user.relevant_volunteerings.select {|v| v.valid?}
    end

    def new_signup
      @volunteering = Volunteering.new(:project_id => params[:project_id], :user_id => current_user.id)

      @project = @volunteering.project
    end

    def new_recruit
      @volunteering = Volunteering.new
      @available_projects = current_user.projects.where(:mission_aligned => true)
      @user = User.find_by(:secure_token => params[:temporary_token])
      @user.secure_token = User.generate_unique_secure_token
      @user.save(:validate => false)
      @token = @user.secure_token
      @skill_names = @user.skill_names_for_display
    end

    def create
      @project = Project.find(volunteering_params[:project_id])
      if volunteering_params[:event] == 'apply'
        @volunteering = Volunteering.create(:project_id => @project.id, :user_id => current_user.id)
        @volunteering.apply!(current_user)
        redirect_to dashboard_volunteerings_path
      elsif volunteering_params[:event] == 'recruit'
        @user = User.find_by(:secure_token => volunteering_params[:secure_token])
        if @user.blank?
          render plain: "The form information you submitted has expired. Please try again or contact an admin for help"
        else
          @volunteering = Volunteering.create(:project_id => @project.id, :user_id => @user.id)
          @volunteering.recruit!(current_user)
          @user.secure_token = User.generate_unique_secure_token
          @user.save(:validate => false)
          redirect_to dashboard_projects_path
        end
      end
    end

    def edit
      @user = resource.user
      @project = resource.project

      if @project.leads.include?(current_user) || @user == current_user
        render :edit
      else
        redirect_to dashboard_volunteerings_path
      end
    end

    def update
      case volunteering_params[:event]
      when 'apply'
        resource.apply!(current_user)
      when 'recruit'
        resource.recruit!(current_user)
      when 'withdraw'
        resource.withdraw!(current_user)
      when 'confirm'
        resource.confirm!(current_user)
      when 'leave'
        resource.leave!(current_user)
      when 'remove'
        resource.remove!(current_user)
      end

      redirect_to edit_dashboard_volunteering_path(resource)

    end

    private

    def volunteering_params
      params.require(:volunteering).permit(:user_id, :project_id, :event, :secure_token)
    end

    def get_contributor_slack_information
      contributor_attributes(resource.project).each do |key, values|
        if values.present?
          values.each do |v|
            v.get_slack_details
            v.save(:validate => false)
          end
        end
      end
    end

end

app/helpers/dashboard/base_helper.rb
module Dashboard::BaseHelper
end

app/helpers/dashboard/users_helper.rb
module Dashboard::UsersHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/dashboard/skills/index.html.erb
<h1>All Skills</h1>
<hr />

<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#tech" role="tab" aria-controls="home" aria-selected="true">Tech Skills</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#nontech" role="tab" aria-controls="profile" aria-selected="false">Non-Tech Skills</a>
  </li>
</ul>

<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="tech" role="tabpanel" aria-labelledby="home-tab">
    <div class="row mt-3">
      <% collection.tech_skills.each_with_index do |skill, idx| %>
        <div class="col">
          <%= link_to skill.name, [:dashboard, skill], :class => "list-group-item list-group-item-action" %>
        </div>
        <%= content_tag(:div, "", :class => "w-100") if (idx + 1) % 3 == 0 %>
      <% end %>
    </div>
  </div>
  <div class="tab-pane fade" id="nontech" role="tabpanel" aria-labelledby="profile-tab">
    
    <div class="row mt-3">
      <% collection.non_tech_skills.each_with_index do |skill, idx| %>
        <div class="col">
          <%= link_to skill.name, [:dashboard, skill], :class => "list-group-item list-group-item-action" %>
        </div>
        <%= content_tag(:div, "", :class => "w-100") if (idx + 1) % 3 == 0 %>
      <% end %>
    </div>
  </div>
  <hr />
</div>

app/views/dashboard/skills/show.html.erb
<h1>Skill: <%= resource.name %></h1>

<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#using" role="tab" aria-controls="home" aria-selected="true">Projects Using this Skill</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#needs" role="tab" aria-controls="profile" aria-selected="false">Projects Needing this Skill</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#users" role="tab" aria-controls="profile" aria-selected="false">Anonymized Users Possessing this Skill</a>
  </li>
</ul>


<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="using" role="tabpanel" aria-labelledby="home-tab">
    <div class="list-group">
      <% @projects_having.each do |project| %>
        <div href="<%= url_for [:dashboard, project] %>" class="list-group-item list-group-item-action flex-column align-items-start">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1"><%= link_to project.name, [:dashboard, project] %></h5>
            <small><%= time_ago_in_words(project.created_at) %> ago</small>
          </div>
          <p class="mb-1"><%= project.description.try(:truncate, 300) %></p>
          <small>Slack Channel: <%= project.slack_channel_for_url.present? ? link_to("##{project.slack_channel}", "slack://channel?team=T1KR8AG7J&id=#{project.slack_channel_for_url}") : "None entered" %></small>
        </div>

      <% end %>
      <%= content_tag(:p, "No Projects Use This Skill Now", :class => "alert alert-success") if @projects_having.blank? %>
    </div>
  </div>
  <div class="tab-pane fade" id="needs" role="tabpanel" aria-labelledby="profile-tab">
    
    <div class="list-group">
      <% @projects_needing.each do |project| %>
        <div href="<%= url_for [:dashboard, project] %>" class="list-group-item list-group-item-action flex-column align-items-start">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1"><%= link_to project.name, [:dashboard, project] %></h5>
            <small>3 days ago</small>
          </div>
          <p class="mb-1"><%= project.description.try(:truncate, 300) %></p>
          <small>Slack Channel: <%= project.slack_channel_for_url.present? ? link_to("##{project.slack_channel}", "slack://channel?team=T1KR8AG7J&id=#{project.slack_channel_for_url}") : "None entered" %></small>
        </div>
      <% end %>
      <%= content_tag(:p, "No Projects Need This Skill Now", :class => "alert alert-success") if @projects_needing.blank? %>
    </div>
    
  </div>

  <div class="tab-pane fade" id="users" role="tabpanel" aria-labelledby="profile-tab">
    
    <div class="list-group">
      <% @users_having.each do |user| %>
        <div class="list-group-item list-group-item-action flex-column align-items-start">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1"><%= link_to "Recruit this User", dashboard_volunteerings_new_recruit_path(:temporary_token => user.secure_token) %></h5>
          </div>
          <p class="mb-1"><%= "Skills: #{user.skill_names_for_display}" %></p>
        </div>
      <% end %>
      <%= content_tag(:p, "No Users in our Anonymized Directory Possess this Skill Now", :class => "alert alert-success") if @users_having.blank? %>
    </div>
    
  </div>
  <hr />
</div>