config/routes.rb
Rails.application.routes.draw do

  root :to => 'welcome#home'

  namespace :dashboard do
    root :to => 'base#index'
    get 'base/index'
    post "/search", to: "base#search"
    get "/search", to: "base#search"
    resource :user, only: [:edit, :update]
    resources :skills, only: [:index, :show]
    resources :projects do
      get 'all', :on => :collection
    end
    resources :volunteerings, only: [:index, :create, :update, :edit]
  end

  # scope :existing do
  #   resources :users, only: [:show]
  # end

  get 'dashboard/volunteerings/new_signup' => 'dashboard/volunteerings#new_signup'

  get 'dashboard/volunteerings/new_recruit' => 'dashboard/volunteerings#new_recruit'

  # get '/welcome/dashboard' => 'welcome#dashboard'
  get '/users/registration' => 'users#registration'
  get 'users/new/confirmation' => 'users#confirmation'
  put 'users/update' => 'users#update'
  get '/welcome/home' => 'welcome#home'


  devise_for :users, except: [:index], controllers: {
    sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks', users: 'users'
  }, :path => 'devise'

  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :users, except: [:index, :destroy, :show]


  post 'slack/search'

  post 'slack/project_search'

  post 'slack/project_skills_search'

  post 'slack/project_list'

  get '/admin/projects/upload_csv', to: 'admin/projects#upload_csv', as: :admin_projects_upload_csv

  get '/admin/users/upload_csv', to: 'admin/users#upload_csv', as: :admin_users_upload_csv

  post 'admin/projects/import_data', to: 'admin/projects#import_data', as: :admin_projects_import_data
        
  post 'admin/users/import_data', to: 'admin/users#import_data', as: :admin_users_import_data

  post 'admin/projects/bulk_post', to: 'admin/projects#bulk_post', as: :admin_projects_bulk_post

  post 'admin/users/bulk_post', to: 'admin/users#bulk_post', as: :admin_users_bulk_post

  # uncomment these lines after rake db:create is finished
  #devise_for :admin_users, ActiveAdmin::Devise.config

  #ActiveAdmin.routes(self)



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/volunteering.rb
class Volunteering < ApplicationRecord
  include AASM
  include Rails.application.routes.url_helpers
  include Syncable

  belongs_to :user
  belongs_to :project

  validates :project, presence: true
  validates :user, presence: true

  validates_uniqueness_of :user_id, :scope => :project_id, :message => "User can only volunteer once per project"

  audited associated_with: :project
  audited associated_with: :user

  attr_accessor :event, :skip_sending_volunteering_updates

  aasm :column => 'state' do
    state :potential, initial: true
    state :signed_up
    state :invited
    state :active
    state :former
    
    event :set_active, after: :send_volunteering_updates do
      transitions from: [:potential, :signed_up, :invited, :resigned, :removed, :former], to: :active, guard: :application_override?
    end

    event :set_former, after: :send_volunteering_updates do
      transitions from: [:potential, :signed_up, :invited, :active, :resigned, :removed], to: :former, guard: :application_override?
    end
    
    event :apply do
      after do
        send_volunteering_email
        send_volunteering_updates
      end
      transitions from: [:potential, :former], to: :signed_up, guard: :user_is_not_lead?
    end
    
    event :recruit, after: :send_recruitment_messages do
      transitions from: [:potential, :former], to: :invited, guard: :user_is_lead?
    end

    event :withdraw, after: :send_volunteering_updates do
      transitions from: [:signed_up, :invited], to: :potential, guard: :user_can_withdraw?
    end

    event :confirm, after: :send_volunteering_updates, guard: :user_can_confirm? do
        transitions from: [:signed_up, :invited], to: :active
    end

    event :leave, after: :send_volunteering_updates do
      transitions from: :active, to: :former, guard: :user_is_volunteer?
    end

    event :remove, after: :send_volunteering_updates do
      transitions from: :active, to: :former, guard: :user_is_lead?
    end

  end

  def application_override?(key)
    key == ENV['AASM_OVERRIDE']
  end

  def user_is_not_lead?(user)
    !self.project.leads.include?(user) and user.is_a? User
  end

  def user_is_lead?(user)
    self.project.leads.include?(user)
  end

  def user_is_volunteer?(user)
    user == self.user
  end

  def user_can_withdraw?(user)
    if self.signed_up?
      user_is_volunteer?(user)
    elsif self.invited?
      user_is_lead?(user)
    end
  end

  def user_can_confirm?(user)
    if self.signed_up?
      user_is_lead?(user)
    elsif self.invited?
      user_is_volunteer?(user)
    end
  end

  def self.get_volunteering_id(project, user)
    volunteering = Volunteering.find_by(:project_id => project.id, :user_id => user.id)

    volunteering.id
  end

  def relevant?
    ['signed_up', 'invited', 'active'].include?(self.state)
  end

  def send_volunteering_email
    project = self.project
    user = self.user

    if project.leads.any? && project.leads.pluck(:email).any?
      if self.state == "signed_up"
        EmailNotifierMailer.with(user: user, project: project, volunteering: self, emails: project.leads.pluck(:email)).new_volunteer_email.deliver_later
      end
    else 
      if !project.flags.include?('this project lacks a lead')
        project.flags << 'this project lacks a lead'
        project.save
      end
    end
  end

  def send_volunteering_updates
    unless self.skip_sending_volunteering_updates
      leads = self.project.leads
      project = self.project
      volunteer = self.user
      coordinators = self.project.progcode_coordinators

      if volunteer.slack_userid
        send_slack_volunteering_notification(user: volunteer, title_link: edit_dashboard_volunteering_url(self), testing: cast_string_to_boolean(ENV['NOTIFICATION_TESTING']))
      end

      if !leads.empty?
        leads.each do |lead|
          send_slack_volunteering_notification(user: lead, title_link: edit_dashboard_volunteering_url(self))
        end
      else
        if !project.flags.include?('this project lacks a lead')
          project.flags << 'this project lacks a lead'
          project.save
        end

        if !coordinators.empty?
          coordinators.each do |coordinator|
            send_slack_volunteering_notification(user: coordinator, title_link: admin_volunteering_url(self))
          end
        else
          if !project.flags.include?('this project lacks a coordinator')
            project.flags << 'this project lacks a coordinator'
            project.save
          end
        end
      end
    end  
  end

  def send_recruitment_messages
    unless self.skip_sending_volunteering_updates
      leads = self.project.leads
      project = self.project
      volunteer = self.user

      attachments = [
        pretext: "Volunteering Recruitment",
        title: "Invitation to join #{self.project.name}"
      ]

      volunteer_attachments = [attachments[0].merge(
        text: "A project lead for #{self.project.name} has seen your skills in Progbot's anonymized directory and invites you to join the project! Click the link to view more details in ProgBot")]

      lead_attachments = [attachments[0].merge(
        text: "An anonymous user from ProgBot has been sent the following slack message: A project lead for #{self.project.name} has seen your skills in Progbot's anonymized directory and invites you to join the project! Click the link to view more details in ProgBot")]

      if volunteer.slack_userid
        send_slack_volunteering_notification(user: volunteer, title_link: edit_dashboard_volunteering_url(self.id), attachments: volunteer_attachments)
      end

      if volunteer.email
        EmailNotifierMailer.with(user: volunteer, project: project, volunteering: self).new_recruit_email.deliver_later
      end

      if leads.present?
        leads.each do |l|
          if l.slack_userid
            send_slack_volunteering_notification(user: l, title_link: edit_dashboard_volunteering_url(self.id), attachments: lead_attachments)
          end
          if l.email
            EmailNotifierMailer.with(user: l, project: project, volunteering: self).new_recruit_email.deliver_later
          end
        end
      end
    end
  end

  def default_slack_attachment
    [
      pretext: "Volunteering Updated",
      title: "#{self.user.slack_username}'s volunteering for #{self.project.name} has been updated",
      text: "#{self.user.slack_username}'s status has been changed from #{self.aasm.from_state} to #{self.aasm.to_state}. Click the link to view more details in ProgBot."
    ]
  end

  def send_slack_volunteering_notification(user:,title_link:,testing: cast_string_to_boolean(ENV['NOTIFICATION_TESTING']), attachments: self.default_slack_attachment)
    base_params = {
      channel: user.slack_userid,
      attachments: attachments
    }

    SlackBot.send_message(SlackBot.merge_params(base_params, {
      attachments: [
        title_link: title_link
      ]
    }), testing = testing)
  end

  def nested_label
    if self.user.slack_username
      "#{self.user.slack_username} (#{self.state})"
    elsif self.user.name
      "#{self.user.name} (#{self.state})"
    elsif self.user.slack_userid
      "#{self.user.slack_userid} (#{self.state})"
    end
  end


end

app/controllers/dashboard/base_controller.rb
class Dashboard::BaseController < ApplicationController
  before_action :authenticate_user!
  layout "dashboard"

  def index

  end

  def search
    @results = {skills: Skill.simple_search(params[:q]), projects: Project.simple_search(params[:q]), users: UserSearch.new({text: params[:q]}).call}
  end
end

app/controllers/dashboard/projects_controller.rb
class Dashboard::ProjectsController < Dashboard::BaseController
  inherit_resources
  include SlackHelpers
  
  def all
    @projects = Project.order("name ASC").includes(:stacks).where(:mission_aligned => true)
  end

  def create
    @project = Project.new(project_params)

    @project.get_ids_from_names(project_params[:tech_stack_names].split(", "), project_params[:non_tech_stack_names].split(", "), project_params[:needs_category_names].split(", "))

    if @project.valid?
      @project.project_created = Time.current
      @project.save
      redirect_to dashboard_projects_path
    else
      render :edit
    end
  end
  
  def show
    @project = Project.find(params[:id])
    @channel = @project.slack_channel_for_url
  end

  def edit
    @channels = SlackHelpers.get_slack_channels
    skills = resource.tech_stack.map{|s| s.name}.join(",")
    print skills
    
  end

  def update

    resource.assign_attributes(project_params)
    
    if params[:slack_channel]
      
      resource.get_slack_channel_id(params[:slack_channel])
    end

    resource.get_ids_from_names(project_params[:tech_stack_names].split(", "), project_params[:non_tech_stack_names].split(", "), project_params[:needs_category_names].split(", "))

    if resource.save
      redirect_to dashboard_projects_path
    else
      render :edit
    end

  end

  private

  
  def begin_of_association_chain
    current_user
  end

  def project_params
    params.require(:project).permit(:name, :description, :website, :slack_channel, :active_contributors, :project_created, :mission_accomplished, :needs_pain_points_narrative, :org_structure, :project_mgmt_url, :summary_test, :repository, :software_license_url, :values_screening, :working_doc, :full_release_features, :attachments, :tech_stack_names, :needs_category_names, :non_tech_stack_names, business_models: [],  legal_structures: [], oss_license_types: [], project_applications: [],  lead_ids: [], status: [], master_channel_list: [])
  end
end

app/controllers/dashboard/skills_controller.rb
class Dashboard::SkillsController < Dashboard::BaseController
  inherit_resources
  before_action :authenticate_user!

  def show
    @projects_having = resource.projects.where(:mission_aligned => true)
    @projects_needing = resource.project_needs.where(:mission_aligned => true)
    @users_having = resource.users.where(:optin => true)
  end

  
end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < Dashboard::BaseController
  inherit_resources
  defaults :singleton => true
  
  def edit
    current_user.valid?
  end

  def update
    if current_user.update(user_params)
      redirect_to dashboard_root_path
    else
      render :edit
    end
  end

  protected
    def resource
      current_user
    end

  private

    def user_params
      params.require(:user).permit(
        :edit, :anonymous, :join_reason,
        :overview, :location, :tech_skill_names, :non_tech_skill_names,
        :optin, :phone, :read_code_of_conduct,
        :verification_urls, :hear_about_us, :is_approved, :gender_pronouns, :additional_info
      )
    end
end

app/controllers/dashboard/volunteerings_controller.rb
class Dashboard::VolunteeringsController < Dashboard::BaseController
    inherit_resources
    include ProjectsHelper

    before_action :get_contributor_slack_information, only: :edit

    def index
      @volunteerings = current_user.relevant_volunteerings.select {|v| v.valid?}
    end

    def new_signup
      @volunteering = Volunteering.new(:project_id => params[:project_id], :user_id => current_user.id)

      @project = @volunteering.project
    end

    def new_recruit
      @volunteering = Volunteering.new
      @available_projects = current_user.projects.where(:mission_aligned => true)
      @user = User.find_by(:secure_token => params[:temporary_token])
      @user.secure_token = User.generate_unique_secure_token
      @user.save(:validate => false)
      @token = @user.secure_token
      @skill_names = @user.skill_names_for_display
    end

    def create
      @project = Project.find(volunteering_params[:project_id])
      if volunteering_params[:event] == 'apply'
        @volunteering = Volunteering.create(:project_id => @project.id, :user_id => current_user.id)
        @volunteering.apply!(current_user)
        redirect_to dashboard_volunteerings_path
      elsif volunteering_params[:event] == 'recruit'
        @user = User.find_by(:secure_token => volunteering_params[:secure_token])
        if @user.blank?
          render plain: "The form information you submitted has expired. Please try again or contact an admin for help"
        else
          @volunteering = Volunteering.create(:project_id => @project.id, :user_id => @user.id)
          @volunteering.recruit!(current_user)
          @user.secure_token = User.generate_unique_secure_token
          @user.save(:validate => false)
          redirect_to dashboard_projects_path
        end
      end
    end

    def edit
      @user = resource.user
      @project = resource.project

      if @project.leads.include?(current_user) || @user == current_user
        render :edit
      else
        redirect_to dashboard_volunteerings_path
      end
    end

    def update
      case volunteering_params[:event]
      when 'apply'
        resource.apply!(current_user)
      when 'recruit'
        resource.recruit!(current_user)
      when 'withdraw'
        resource.withdraw!(current_user)
      when 'confirm'
        resource.confirm!(current_user)
      when 'leave'
        resource.leave!(current_user)
      when 'remove'
        resource.remove!(current_user)
      end

      redirect_to edit_dashboard_volunteering_path(resource)

    end

    private

    def volunteering_params
      params.require(:volunteering).permit(:user_id, :project_id, :event, :secure_token)
    end

    def get_contributor_slack_information
      contributor_attributes(resource.project).each do |key, values|
        if values.present?
          values.each do |v|
            v.get_slack_details
            v.save(:validate => false)
          end
        end
      end
    end

end

app/helpers/dashboard/base_helper.rb
module Dashboard::BaseHelper
end

app/helpers/dashboard/users_helper.rb
module Dashboard::UsersHelper
end

app/views/dashboard/volunteerings/edit.html.erb
<h1>Volunteer: <%= ["signed_up", "active"].include?(resource.state) ? (link_to @user.slack_username, "slack://user?team=T1KR8AG7J&id=#{@user.slack_userid}") : "Anonymous" %></h1>

<h1>Project: <%= link_to @project.name, dashboard_project_path(@project.id) %>

<h1>Status: <%= resource.state.humanize %></h1>

<h2>Project Contact Information:</h2>
  <ul>
    <% if @project.slack_channel.present? %>
      <li>Project Slack Channel: <%= link_to @project.slack_channel, 'slack://channel?team=T1KR8AG7J&id=' + @project.slack_channel %></li>
    <% end %>
    <% contributor_attributes(@project).each do |key, values|%>
      <% if ['leads', 'progcode_coordinators'].include?(key) %>
        <% if values.present? %>
          <li><%= key.humanize %>:
            <ul>
              <% values.each do |v| %>
                <% if v.has_slack? %>
                  <li>Slack: <%= link_to v.slack_username, 'slack://user?team=T1KR8AG7J&id=' + v.slack_userid %></li>
                <% end %>
                <% if v.email.present? %>
                  <li>Email: <%=mail_to v.email %></li>
                <% end %>
              <% end %>
            </ul>
          </li>
        <% end %>
      <% end %>
    <% end %>

  </ul>

<h2>Volunteer's Tech Skills:</h2>

<% @user.tech_skills.each do |skill| %>
  <ul>
   <h3> <li><%= link_to skill.name, dashboard_skill_path(skill) %></li></h3>
  </ul>
<% end %>

<h2>Volunteer's Non Tech Skills:</h2>

<% @user.non_tech_skills.each do |skill| %>
  <ul>
  <h3><li><%= link_to skill.name, dashboard_skill_path(skill) %></li></h3>
  </ul>
<% end %>

<%= simple_form_for([:dashboard, resource]) do |f| %>

  <%= f.input :event, :label => 'Edit Status', collection: resource.aasm.events({permitted: true}, current_user).map(&:name) %>

  <%= f.button :submit %>

<% end %>

app/views/dashboard/volunteerings/index.html.erb
<div class="table-responsive">
  <table class="table table-bordered table-striped table-sm">
    <thead>
      <tr>
        <th>Manage</th>
        <th>Project</th>
        <th>Volunteering Status</th>
        <th>Slack Channel</th>
        <th>Project Lead(s)</th>
      </tr>
    </thead>
    <tbody>
      <% @volunteerings.each do |volunteering| %>
        <% project = volunteering.project %>
        <tr>
          <td><%= link_to volunteering.id, edit_dashboard_volunteering_path(volunteering) %></td>
          <td><%= link_to project.name, dashboard_project_path(project) %></td>
          <td>
            <%= volunteering.state.humanize %>
          </td>
          <td>
            <% if project.slack_channel %>
              <%= link_to '#' + project.slack_channel, 'slack://channel?team=T1KR8AG7J&id=' + project.slack_channel %>
            <% end %>
          </td>
          <td>
            <% project.leads.each do |lead| %>
              <%= link_to lead.name, 'slack://user?team=T1KR8AG7J&id=' + lead.slack_userid %>
            <% end %>
          </td>
        </tr>
      <% end %>
      
    </tbody>
  </table>
</div>

app/views/dashboard/volunteerings/new.html.erb
<%= simple_form_for([:dashboard, @volunteering], :url => { :action => "create" }) do |f| %>

<%= f.hidden_field :project_id %>
<%= f.hidden_field :event, :value => 'apply' %>

<%= f.hint "You are signing up to volunteer for #{@project.name}. The project leads will be notified of your interest and asked to confirm. By Clicking the button below you are agreeing to share your slack profile and skills with the project leads of 
#{@project.name}."%>

<%= f.button :submit, "Volunteer" %>

<% end %>

app/views/dashboard/volunteerings/new_recruit.html.erb
<% if @available_projects.present? %>
  <h1>Recruit a User to Your Project</h1>
  <%= simple_form_for([:dashboard, @volunteering], :url => { :action => "create" }) do |f| %>

  <%= f.hidden_field :secure_token, :value => @token %>
  <%= f.hidden_field :event, :value => 'recruit' %>
  <%= f.input :project_id, collection: @available_projects, label: "Choose One of Your Projects", hint: "You can only recruit volunteers to approved projects of which you are a lead. If you have any questions about this, contact <a href='mailto:admin@progcode.org'>admin@progcode.org</a>".html_safe %>

  <%= f.hint "By clicking the button below, you are recruiting a user possessing the skills <strong>#{@skill_names}</strong> to participate in the selected project. This user will receive a message via slack and e-mail inviting them to join the project. They will be given the e-mail addresses and slack usernames of all project leads should they wish to make contact. You will receive a copy of this invitation.".html_safe %>

  <%= f.button :submit, "Recruit" %>

  <% end %>
<% else %>
  <p>In order to recruit a volunteer, you must be the lead on a project that has been approved as mission aligned. Think there's been a mistake? Contact <a href="mailto:admin@progcode.org">admin@progcode.org</a>.</p>
<% end %>

app/views/dashboard/volunteerings/new_signup.html.erb
<%= simple_form_for([:dashboard, @volunteering], :url => { :action => "create" }) do |f| %>

<%= f.hidden_field :project_id %>
<%= f.hidden_field :event, :value => 'apply' %>

<%= f.hint "You are signing up to volunteer for #{@project.name}. The project leads will be notified of your interest and asked to confirm. By Clicking the button below you are agreeing to share your slack profile and skills with the project leads of 
#{@project.name}."%>

<%= f.button :submit, "Volunteer" %>

<% end %>