config/routes.rb
Rails.application.routes.draw do

  root :to => 'welcome#home'

  namespace :dashboard do
    root :to => 'base#index'
    get 'base/index'
    post "/search", to: "base#search"
    get "/search", to: "base#search"
    resource :user, only: [:edit, :update]
    resources :skills, only: [:index, :show]
    resources :projects do
      get 'all', :on => :collection
    end
    resources :volunteerings, only: [:index, :create, :update, :edit]
  end

  # scope :existing do
  #   resources :users, only: [:show]
  # end

  get 'dashboard/volunteerings/new_signup' => 'dashboard/volunteerings#new_signup'

  get 'dashboard/volunteerings/new_recruit' => 'dashboard/volunteerings#new_recruit'

  # get '/welcome/dashboard' => 'welcome#dashboard'
  get '/users/registration' => 'users#registration'
  get 'users/new/confirmation' => 'users#confirmation'
  put 'users/update' => 'users#update'
  get '/welcome/home' => 'welcome#home'


  devise_for :users, except: [:index], controllers: {
    sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks', users: 'users'
  }, :path => 'devise'

  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :users, except: [:index, :destroy, :show]


  post 'slack/search'

  post 'slack/project_search'

  post 'slack/project_skills_search'

  post 'slack/project_list'

  get '/admin/projects/upload_csv', to: 'admin/projects#upload_csv', as: :admin_projects_upload_csv

  get '/admin/users/upload_csv', to: 'admin/users#upload_csv', as: :admin_users_upload_csv

  post 'admin/projects/import_data', to: 'admin/projects#import_data', as: :admin_projects_import_data
        
  post 'admin/users/import_data', to: 'admin/users#import_data', as: :admin_users_import_data

  post 'admin/projects/bulk_post', to: 'admin/projects#bulk_post', as: :admin_projects_bulk_post

  post 'admin/users/bulk_post', to: 'admin/users#bulk_post', as: :admin_users_bulk_post

  # uncomment these lines after rake db:create is finished
  #devise_for :admin_users, ActiveAdmin::Devise.config

  #ActiveAdmin.routes(self)



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admin/partials/_import_success.html.erb
<div class="list-head">
  <div class="page-header page-header-002">
    <h1><%= controller_name.titleize %> Successfully Imported!</h1>
  </div><!-- page-header -->
  <div class="filter">
    <h2><%= "#{resources.length} #{controller_name} have been created/updated"  %></h2>
  </div>
</div>
<div>
  <table class="table">
    <thead>
      <tr>
        <% attributes.each do |attr| %>
          <th scope="col"><%= attr %></th>
        <% end %>
      </tr>
    </thead>
    <% if resources.any? %>
      <tbody>
        <% resources.each do |resource| %>
          <tr>
            <% attributes.each do |attr| %>
              <td><%= resource[attr] %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    <% end %>
  </table>
</div>

app/views/admin/partials/_upload_csv.html.erb
<h1>Import <%= controller_name.singularize.titleize %> Data from Airtable</h1>
<%= form_tag({:controller => controller_path, :action => 'import_data'}, multipart: true) do %>
    <div class="row"><%= file_field_tag :file, :class => "btn" %></div>
    <%# <div class="row"><%= label_tag 'airtable_type_prog_apps', 'From Prog Apps Table' %>
    <%# <%= radio_button_tag 'airtable_type', 'prog_apps', true %>
    <%# </div> %>
    <div class="row">
    <%# <%= label_tag 'airtable_type_admin', 'From Admin Table' %>
    <%# <%= radio_button_tag 'airtable_type', 'admin' %>
    <%# </div> %>
    <div class="row"><%= hidden_field_tag :confirmation, "pending" %>
    <%= submit_tag "Import", :class => "btn", :disabled => true %></div>
<% end %>